"""empty message

Revision ID: 62838bc5994e
Revises: 77c095a6bfa4
Create Date: 2020-02-22 10:07:18.088870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62838bc5994e'
down_revision = '77c095a6bfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'seeking_venues')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
